spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alibou_workshops
    driver-class-name: org.postgresql.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    # user:
    # password:
    baseline-description: "init"
    baseline-version: 1

